server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practicaMod3
    username: postgres
    password: jpma
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration,classpath:dev/db/migration